apiVersion: v1
kind: Service
metadata:
  name: bank-receiver-consents-api
spec:
  selector:
    app: bank-receiver-consents-api
  ports:
    - port: 3334
      targetPort: 3334
  type: LoadBalancer
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-receiver-consents-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-receiver-consents-api
  template:
    metadata:
      labels:
        app: bank-receiver-consents-api
    spec:
      containers:
        - name: app
          image: benisson/bank-receiver-consents-api:0.0.1
          ports:
            - containerPort: 3334
          env:
            - name: BACK_RECEIVER_DB_CONSENT_USER
              value: bank-receiver-consent-db-user
            - name: BACK_RECEIVER_DB_CONSENT_PASS
              value: bank-receiver-consent-db-pass
            - name: BACK_RECEIVER_DB_CONSENT_PORT
              value: "3307"
            - name: BACK_RECEIVER_DB_CONSENT_HOST
              value: bank-receiver-consent-db
            - name: BACK_RECEIVER_DB_CONSENT_NAME
              value: bank-receiver-consent-db
            - name: RABBIT_MQ_URL
              value: rabbitmq
            - name: URL_BANK_TRANSMITTER
              value: http://bank-transmitter-consents-api:3333/bank-transmitter
            - name: URL_BANK_RECEIVER
              value: http://bank-receiver-consents-api:3334/bank-receiver
            - name: KEY_JWS
              value: "@key_pass#"
            - name: RABBIT_MQ_URL
              value: localhost
            - name: RABBIT_MQ_URL_DOCKER
              value: rabbitmq
            - name: RABBIT_MQ_PORT
              value: "5672"
            - name: RABBIT_MQ_PASS
              value: guest
            - name: RABBIT_MQ_USER
              value: guest
          imagePullPolicy: Always
      restartPolicy: Always
